apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/adrian.martin/.minikube/ca.crt
    server: https://192.168.39.197:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/adrian.martin/.minikube/client.crt
    client-key: /home/adrian.martin/.minikube/client.key