apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOUTdraWFNV3cvVVdBVHNXdHByCmJNNDBhQ3FKUUp1a0hGWnB6Z2p0aCt3VUs0SEFyRExnU09iRzUxMUN3TDBHTWRZTlpZcGNDNFJhUVloT3dIcG8KNHluNDRSSkRDQlpzVVFQQ1NNckNpc2xmOGJoRWFMV3FTcjBGZWRRYjNtOHY3aVYzYXFVRWVKbXl5ZUZidWthNwpPNEk5bUE1cWZNMm8yWTYweFY2YWR6bnRnVi94NE9SZjFhM3U3WmRVT24yNDlIc0lPSm5VVUZCZGdJNmZaTUhvCjFhNXhWN2VwQU1wS2tKVFNLVE1WWUFUYmlMRkFMcW4zNU5YUlFEZWRFWm9sU1ViaE1sUnE4SjlMcWpIN29BN3gKK09od1kxTDJpd2svOFhDYWVkaFAwSU0rUlFnUnZKeTkrKzNvbk14Y0NjMHNPUnhNeXhQMzZPS1EvR2Q3dS92QwpXYmtDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNJelR3ME05Z2lTRmxSR2R2SzFtejF1UUZ6Cng2elNFT0J2aXFiMlg5RVI2UUtnbXliZFBOVzc2cmY3ZEMrZmhnU2VNakIzTU9ydFFOYjNXd04wUmhJU0N0dE4KVzVyVWVGZ1Uxb3hpdTh4T3ArQUEyOGRDV0pKOG1BUHpldU5tQitQYlROajhLQURKVjYvZkJob0owTUZoeHREbgpJSWNUWHAxNXpXODMrRkJxNmRIeEdFblo5Z1dXVDRmcUtLbzN5UlVaSnBYUFR0TllIRXFGd2JtWHRMSjFFY0NnCmJkNzdDOUx3U21DQit0TXg3WkIyVjQ5N0ZHdTVKTU0zM3l0Rm5VS2ZOTDZQMXN1emNpU0NGaDhlTGNxeXhOeHgKQks1KzU5MGpDK1NpM1VmRTEwVCtoQzFxdkZuMHBhSUk2VDBLT0I3RUlpT2VWelZ0SjUvTVhLbTJzQzVPCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - client auth