apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQRFF3UHA2VXVSOXFxb2tRRUpGCmJRMnI0dDkycWFwVVZac3BrWTN1WlB4cCswSWlIN1hkeDJ5QkFSQy9QUEcwd0hsOWRHWlR2c3B2di9MNGVnRmsKRU1rTHcvcEUzd3cwUjdIWVNZZEl6aUdJMHRRNHJOV2MzS3doWE82WlNoVFJyL1ArZm5vOFpSQkhwUzRGMGloRgo0Z1E1ZmtEaStudkpiUXJ1czFjbFdKYmk1cFBhcTNEZ3dtc2k3SVBXT1ZuUFlyd29ZSEZ4ZGFsZm9sT1NlQzBQCkw4ZVVsMm9uVG9lSzZETzVHNy9zVXMvTUtMOFpCOGM4ZGVuS3R2Zk5PaCtNaElFYlZiMWR6YWJsV1Awc0liU3oKS3kwM1RCU0tGcXovZnNlRDdFWDFmTTJONWwzbHNhODJ5aXY3a3BJWXQ5Y1o3cm5JbmVaM2xlRE91NHkyaU1NWQphR1VDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNldXdVY0w0bWExTHVvcGJsRUpSRTVzeFRwCkJSVWhoSVI5d3dDekhBWUhaazFCUzBRWXNBRHZwTkpBUWt5N0lzRlVOU054bURGejNqSlpqMUd2a09Bb3VPVjIKV0dTcGpodTVHbjg4VXd2RlV5WDJYajRVMkJPcUJPMjg4YWlpdUNOc2RYek5RTC9mVGpHdzk0QTIyYXUrVCtpOQpqVVo3WkwvNXVUcnhPTzU0UVVjRHBleDJtMFhFT3FLTC8rNUs2OG5lTW0rUmhpQzlVT05JWWMySS9mRWFNcDFWCkxON2d0UUl6eFNOMXZWdGJRMWRWcW50dFhidEp0a0lNWGhNUFR5VkJEbytaYTErT1NVM0o3ZzZBUThvVHNGS3AKS05NankwN2lmZnkxVEJNMVg1MFBCRTdaRWJ4VUhXU0lLaWJEbzN4bEU0NGhVMjl5d1FHaGtuK3JNcXNwCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - client auth